# H2
spring.datasource.url=jdbc:h2:mem:bibliotecadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Flyway
spring.flyway.locations=classpath:db/migration

# Swagger — sem essas linhas o Swagger não abre
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# MinIO
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=biblioteca-pdfs